# Digital Signal Processing
## Convolution and Correlation

### MsCV - ViBOT - MAIA

In [3]:
%matplotlib inline
%pprint off

# To make some nice plot
import matplotlib.pyplot as plt
# To play with arrays
import numpy as np
from skimage import io
from skimage import img_as_float
from matplotlib import cm

Pretty printing has been turned OFF


## Exercise 1- 1D Convolution

**1.1** Defining a signal $x$ and an impulse response $h$ as parameters, write a program `conv_fn` to compute the convolution product $y=h*x$. Do not use the python or matlab function and just consider zero padding to solve the border problem.

**1.2** Test your function, while using the following signal ($x[n] = \{\underline{1},2,3,4\}$) and following filters, ($\delta[k]$, $H[k]$, $e^{k}$, and $h = \{-1, 1\}$), respectively.

**1.3** Consider the previous input signal, write it's extended version while considering `symmetry`, `periodic` and `constant values` padding and $h = H[k-5]$



In [21]:
def conv_fn (x, h):
    total_len = len(x) + 2*len(h)
    pad = np.zeros(total_len)
    pad[0:len(x)] = x[0:len(x)]
    y = np.zeros((total_len,))
    
    for i in range(0,len(pad)):
        for j in range (0, len(h)):
            y[i] += pad[i-j] * h[j]
    return y
        


In [23]:

def dirac(n=0, N=20):
    s = np.zeros((N,))
    s[n] = 1
    return s

def step (n=0, N=20):
    s = np.zeros((N,))
    for idx in np.arange(n, N):
        s[idx] = 1
    return s

def exp (n=0, N=20):
    s = np.zeros((N,))
    e = 2.718
    for incr, idx in enumerate (np.arange(n, N)):
        s[idx] = e ** incr
    return s


x = np.array([1, 2, 3, 4])
h1 = dirac(0,5)
h2 = step(0,5)
h3 = exp(0,5)
print 'my answer: (dirac filtering) '
print conv_fn(x, h1)
print 'solution: (dirac filtering) '
print np.convolve(x,h1)
print 'my answer: (step filtering) '
print conv_fn(x, h2)
print 'solution: (step filtering) '
print np.convolve(x,h2)
print 'my answer: (exp filtering) '
print conv_fn(x, h3)
print 'solution: (exp filtering) '
print np.convolve(x,h3)

my answer: (dirac filtering) 
[ 1.  2.  3.  4.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
solution: (dirac filtering) 
[ 1.  2.  3.  4.  0.  0.  0.  0.]
my answer: (step filtering) 
[  1.   3.   6.  10.  10.   9.   7.   4.   0.   0.   0.   0.   0.   0.]
solution: (step filtering) 
[  1.   3.   6.  10.  10.   9.   7.   4.]
my answer: (exp filtering) 
[   1.            4.718        15.823524     47.00833823  127.76866331
  198.9389884   244.04369348  218.3020434     0.            0.            0.
    0.            0.            0.        ]
solution: (exp filtering) 
[   1.            4.718        15.823524     47.00833823  127.76866331
  198.9389884   244.04369348  218.3020434 ]


## Exercise 2- 2D Convolution

**2.1** Define a 2D convolution function (Only consider zero-padding the image)

**2.2** Using your function, smooth the `lena` image with the following Gaussian kernel:
$$ K = \frac{1.}{256}\begin{bmatrix} 1 & 4 & 6 & 4 & 1 \\ 4 & 16 & 24 & 16 & 4 \\ 6 & 24 & 36 & 24 & 6 \\ 4 & 16 & 24 & 16 & 4 \\ 1 & 4 & 6 & 4 & 1 \end{bmatrix}$$

**2.3** Apply sobel filtering using convolution


In [27]:
#def conv_2D (x, h):
 #   total_array = size(x)+2*size(h)


    


SyntaxError: invalid syntax (<ipython-input-27-2a8bd4a7a271>, line 4)

## Exercise 3 - Character recognition using cross-correlation

**3.1** load `a.png` and `text.png` images and binarized them using [`threshold_otsu`](http://scikit-image.org/docs/dev/api/skimage.filters.html?highlight=filters#skimage.filters.threshold_otsu)

**3.2** Use [`signal.correlate2d`](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.signal.correlate2d.html#scipy.signal.correlate2d) from `scipy` to correlate your binarized images.
**Note, signal correspond to the bright pixels within and image (invert your masks)**

**3.3** Find the first 10 characters recognized as `a`.